spring:
  application:
    name: poc-r2dbc
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/test
    username: admin
    password: test

management:
  endpoints:
    web:
      exposure:
        includ: "*"